# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello <- function() {
    .Call('_psimtools_rcpp_hello', PACKAGE = 'psimtools')
}

#' Account balances
#'
#' @param balance vector to store balances
#' @param C Cash flow
#' @param r Returns
#' @return Balances
#' @export
fnC <- function(balance, C, r) {
    .Call('_psimtools_fnC', PACKAGE = 'psimtools', balance, C, r)
}

